#!/bin/bash
set -e
###################################################################################
# Written to be used on 64 bits computers
# Name:			0-installation-summary-v1.sh
# Author:		Romano Woodfolk
# Created:		February 13, 2019
# Modified:		March 05, 2019 (110100100)
# Version:		1.0.0
# Website 	: 	http://www.romanowoodfolk.com
#---------------------------------------------------------------------------------#
# Comments: This script contains the installation commands for Linux Mint 19.1
# “Tessa” Cinnamon Edition an ubuntu based distributions.
#---------------------------------------------------------------------------------#
#
echo -e ""; clear; echo -e ""														# clear Screen
echo -e "...installing audio & video applications"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "         ****** Linux Mint Cinnamon Build Script Summary ******                  "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " Audio and Video"
echo -e " Communication and News"
echo -e " Productivity (Office)"
echo -e " Games"
echo -e " Graphics and Photography (GRAPHICS)"
echo -e " Add-ons"
echo -e " Developer Tools (PROGRAMMING)"
echo -e " Education and Science (Education/Science)"
echo -e " Utilities (System Tools/Accessories)"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Package Management Tools ******                               "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " synaptic - Graphical package manager"
echo -e " gdebi - simple tool to \install deb files - GNOME GUI"
echo -e " snappy - snap packages a software deployment and package management system "
echo -e "    originally designed and built by Canonical \for the Ubuntu phone operating "
echo -e "    system."
echo -e " Flatpak - a software utility \for software deployment, package management, "
echo -e "    and application virtualization \for Linux desktop computers. "
echo -e " AppImage - a universal software package format"
echo -e " ubuntu-mate-welcome - Welcome screen \for Ubuntu MATE"
echo -e " parrot-package-manager - Graphical Package Manager \for Parrot OS"
echo -e " Software Boutique - Welcome screen \for Ubuntu MATE"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** AuDIO & Video ******"
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " Audacity -  a free, easy-to-use, multi-track audio editor and recorder"
echo -e " Banshee - Media Management and Playback application"
echo -e " Cheese - uses your webcam to take photos and videos, applies fancy special "
echo -e "      effects and lets you share the fun with others."
echo -e " Clementine - a multiplatform music player focusing on a fast and easy-to-use"
echo -e "      interface for searching and playing your music. "
echo -e " dvd::rip - perl front end for transcode and ffmpeg"
echo -e " EasyTAG - View and edit tags for MP3, MP2, MP4/AAC, FLAC, Ogg Opus, Ogg Speex, "
echo -e "      Ogg Vorbis, MusePack, Monkey's Audio and WavPack files."
echo -e " gtkpod - manage songs and playlists on an Apple iPod"
echo -e " HandBrake - a versatile, easy-to-use tool for converting DVDs and other videos"
echo -e "      into H.264, XViD, or Ogg formatted media "
echo -e " K3b was created to be a feature-rich and easy to handle CD burning application "
echo -e " Kazam - Record a video or take a screenshot of your screen"
echo -e " kdenlive - a non-linear video editing suite, which supports DV, HDV and many more "
echo -e "  formats"
echo -e " kino - Non-linear editor for Digital Video data"
echo -e " mplayer - movie player for Unix-like systems"
echo -e " OBS - OBS Studio is designed for efficiently recording and streaming live video "
echo -e "      content. It supports live RTP streaming to various streaming site"
echo -e " OpenShot Video Editor - a free, open-source, non-linear video editor. It can "
echo -e "      create and edit videos and movies using many popular video, audio, and image "
echo -e "      formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, iPod, Xbox, and "
echo -e "      many more common formats"
echo -e " PulseAudio Volume Control - PulseAudio Volume Control (pavucontrol) is a simple"
echo -e " Rhythmbox - a music management application, designed to work well under the "
echo -e "      GNOME desktop"
echo -e " SimpleScreenRecorder - a feature-rich screen recorder that supports X11 and OpenGL"
echo -e " smplayer - A great media player"
echo -e " sound-juicer - GNOME CD Ripper"
echo -e " Videos (Totem) - Simple media player for the GNOME desktop based on GStreamer"
echo -e " vlc - multimedia player and streamer"
echo -e " xine - an X11 based GUI for the libxine video player library"
echo -e ""
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "               ****** Other ******"
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e ""
echo -e " GTK+ based volume control tool (mixer) for the PulseAudio sound server"
echo -e " GStreamer Multimedia-Codecs"
echo -e " xmms2 - Client/server based media player system"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Communication & News (INTERNET/Networking) ******             "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " Empathy - GNOME multi-protocol chat and call client "
echo -e " Etherape - a graphical network monitor modeled after etherman"
echo -e " Flash Player - Adobe Flash Player plugin installer"
echo -e " Filezilla - Full-featured graphical FTP/FTPS/SFTP client"
echo -e " Firefox Web Browser - Browse the World Wide Web"
echo -e " Evolution - groupware suite with mail client and organizer"
echo -e " Hex Chat - an easy to use yet extensible IRC Client (IRC Client)"
echo -e " Liferea - a (Linux Feed Reader)is a news aggregator for online news feeds "
echo -e " Pidgin Internet Messenger - a chat program which lets you log in to accounts on "
echo -e "   multiple chat networks simultaneously"
echo -e " PuTTY - PuTTY SSH Client is the Unix port of the popular Windows SSH client"
echo -e " Remmina - a remote desktop client"
echo -e " remmina - GTK+ Remote Desktop Client"
echo -e " remmina-common - Common files for Remmina"
echo -e " remmina-dev - Headers for Remmina"
echo -e " remmina-plugin-rdp - RDP plugin for Remmina"
echo -e " remmina-plugin-secret - Secret plugin for Remmina"
echo -e " remmina-plugin-vnc - VNC plugin for Remmina"
echo -e " remmina-plugin-exec - EXEC plugin for Remmina"
echo -e " remmina-plugin-nx - NX plugin for Remmina"
echo -e " remmina-plugin-spice - Spice plugin for Remmina"
echo -e " remmina-plugin-telepathy - Telepathy plugin for Remmina"
echo -e " remmina-plugin-xdmcp - XDMCP plugin for Remmina"
echo -e " Remmina-plugin-gnome - Gnome plugin for Remmina"
echo -e " Remote Desktop Viewer - Vinagre shows remote Windows, Mac OS X and Linux desktops"
echo -e " Transmission -  lightweight BitTorrent clients (in GUI, CLI and daemon form)"
echo -e "   Windows PCs, Apple PCs and various other platforms, including Android and iPhone"
echo -e " Telegram - Telegram Desktop is a messaging app with a focus on speed and security,"
echo -e "   it is super-fast, simple and free"
echo -e " Wicd - Wicd Network Manager is a general-purpose network configuration server which"
echo -e "   aims to provide a simple but flexible interface for connecting to networks"
echo -e " Wireshark - (network \ sniffer) that captures and analyzes packets off the wire"
echo -e " XChat -IRC client for X similar to AmIRC"
echo -e " Zenmap - a Nmap frontend"
echo -e ""
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "               ****** Other ******"
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e ""
echo -e " Google Chrome - The web browser from Google"
echo -e " Skype - client for Skype VOIP and instant messaging service "
echo -e " Synology Assistant- Synology Assistant"
echo -e " Teamviewer - easy, fast and secure remote access and meeting solutions to Linux, "
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Google Chrome ******                                          "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Skype ******                                                  "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Synology Assistant ******                                     "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Teamviewer ******                                             "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** Productivity (Office) ******"
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " calendar - GNOME Calendar is a simple and beautiful calendar application designed"
echo -e "   to perfectly fit the GNOME desktop"
echo -e " calibre - one stop solution to all your e-book needs"
echo -e " calibre E-book Editor - allows you to edit the text and styles inside the book "
echo -e "   with a live preview of your changes"
echo -e " Document Viewer -  Evince (Document Viewer) is a simple multi-page document viewer"
echo -e " gLabels - a program for creating labels and business cards"
echo -e " Gnucash - provides accounting functions suitable for use by small businesses and "
echo -e "   individuals"
echo -e " Gramps - a genealogy program that is both intuitive for hobbyists and feature-"
echo -e "   complete for professional genealogists"
echo -e " HomeBank - a fast, simple and easy to use program to manage personal accounting"
echo -e " LibreOffice is a full-featured office productivity suite that provides a near "
echo -e "   drop-in replacement for Microsoft(R) Office"
echo -e " LibreOffice Base - Database manager part of the LibreOffice productivity suite"
echo -e " LibreOffice Calc - Spreadsheet program of the LibreOffice productivity suite"
echo -e " LibreOffice Impress - Presentation program of the LibreOffice productivity suite"
echo -e " LibreOffice Math - Create and edit scientific formulas and equations by using Math"
echo -e " LibreOffice Writer - Word processor part of the LibreOffice productivity suite"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Games ******                                                  "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " GNOME Mahjongg - a solitaire version of the classic Eastern tile game"
echo -e " GNOME Mines - a puzzle game where you search for hidden mines"
echo -e " GNOME Sudoku - a popular Japanese logic game"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Graphics and Photography (GRAPHICS) ******                    "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " Blender - an integrated 3d suite for modelling, animation, rendering, post-"
echo -e "   production, interactive creation and playback (games)"
echo -e " calibre - E-book Viewer - Read e-books in over a dozen different formats"
echo -e " Darktable - manages your digital negatives in a database and lets you view them "
echo -e "   through a lighttable."
echo -e " Dia - an editor for diagrams, graphs, charts etc"
echo -e " Document Viewer - Evince - is a simple multi-page document viewer"
echo -e " GNU Image Manipulation Program - "
echo -e " Gpick - an application that allows you to sample any color from anywhere on the "
echo -e "   desktop, and use it to create palettes (i.e. collections of colors) for use in "
echo -e "   graphic design applications"
echo -e " Inkscape - an illustration editor which has everything needed to create professional"
echo -e "   quality computer art"
echo -e " Krita -  Digital Painting, Creative Freedom full-featured digital art studio"
echo -e " LibreCAD - an application for computer aided design (CAD) in two dimensions (2D)"
echo -e " LibraOffice Draw - an easy-to-use graphics editor, which empowers you to create "
echo -e "   anything from quick sketches to complex diagrams"
echo -e " LRF Viewer - Viewer for LRF files (SONY ebook format files)"
echo -e " Scribus -  a desktop publishing application that allows you to create posters, mag-"
echo -e "   azines and books ready to send off to a printing house"
echo -e " Shotwell - an easy-to-use, fast photo organizer designed for the GNOME desktop"
echo -e " Simple Scan - Scan Documents"
echo -e " Sweet Home3D - 3D is an interior design Java application for quickly choosing and "
echo -e "   placing furniture on a house 2D plan drawn by the end-user, with a 3D preview."
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Add-ons ******                               "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " GStreamer Multimedia Codecs - GStreamer plugins from the \"ugly\" set"
echo -e " GStreamer Multimedia Codecs - libav plugin for GStreamer"
echo -e " GStreamer Multimedia Codecs - GStreamer plugin for GTK+3"
echo -e " GStreamer Multimedia Codecs - GStreamer plugins from the \"good\" set"
echo -e " GStreamer Multimedia Codecs - GStreamer plugins for X11 and Pango"
echo -e " GStreamer Multimedia Codecs - GStreamer plugin for PulseAudio"
echo -e " GStreamer Multimedia Codecs - GStreamer plugins for GL"
echo -e " GStreamer Multimedia Codecs - GStreamer plugins from the \"base\" set"
echo -e " GStreamer Multimedia Codecs - GStreamer plugin for ALSA"
echo -e " GStreamer Multimedia Codecs - "
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Developer Tools (PROGRAMMING) ******                          "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " Anjuta DevStudio - a versatile software development studio featuring a number"
echo -e "   of advanced programming facilities including project management, application"
echo -e "   wizard, interactive debugger, source editor, version control, GUI designer, "
echo -e "   profiler and many more tools"
echo -e " Arduino IDE - an open-source electronics prototyping platform based on flexible,"
echo -e "   easy-to-use hardware and software. It's intended for artists, designers, "
echo -e "   hobbyists, and anyone interested in creating interactive objects or environments"
echo -e " Bluefish Editor - a powerful editor targeted towards programmers and web "
echo -e "   developers, with many options to write websites, scripts and programming code."
echo -e " Eeschema - Eeschema (Kicad) is a suite of programs for the creation of printed"
echo -e "   circuit boards"
echo -e " GNU Radio Companion - Software Defined Radio (SDR) GUI for programming the GNU "
echo -e "   Radio toolkit"
echo -e " Kicad is made up of 5 main components:"
echo -e "   kicad - project manager, eeschema - schematic editor, pcbnew - PCB editor,  "
echo -e "   gerbview - GERBER viewer, cvpcb - footprint selector for components"
echo -e " +Libraries:"
echo -e "   Both eeschema and pcbnew have library managers and editors for their components "
echo -e "   and footprints. You can easily create, edit, delete and exchange library items."
echo -e "   Documentation files can be associated with components, footprints and key words, "
echo -e "   allowing a fast search by function. Very large libraries are available for "
echo -e "   schematic components and footprints. Most components have corresponding 3D models."
echo -e " Fritzing - an open source project designed to help one transition from a prototype"
echo -e "   to a finished project"
echo -e " Geany - a small, fast and lightweight integrated development environment (IDE) "
echo -e "   using GTK+"
echo -e " Visual Studio Code - a new choice of tool that combines the simplicity of a code "
echo -e "   editor with what developers need for the core edit-build-debug cycle"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Visual Studio Code ******                                     "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Education and Science (Education/Science) ******              "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " LibreOffice Math - an equation editor component for LibreOffice"
echo -e " Stellarium - Desktop Planetarium renders 3D photo-realistic skies in real time "
echo -e "   with OpenGL"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Utilities (System Tools/Accessories) ******                   "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible "
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " ConvertAll - convert any unit in the large database to any other compatible unit"
echo -e " Backup - Déjà Dup Backup Tool -  a simple backup tool"
echo -e " File Roller - Engrampa Archive Manager (also known as File Roller) is the de-"
echo -e "   fault GNOME application for opening, creating, and modifying archive and "
echo -e "   compressed archivefiles."
echo -e " Gip IP Address Calculator - tools for IP address based calculations"
echo -e " Gnome Boxes - Simple GNOME app to access remote or virtual systems"
echo -e " GNOME Disks - Disks - provides an easy way to inspect, format, partition, and "
echo -e "   configure disks and block devices"
echo -e " KeePassXC - an application for people with extremely high demands on secure "
echo -e "   personal data management"
echo -e " Network Tools - GNOME Nettool is a network information tool which provides user"
echo -e "   interfaces for some of the most common command line network tools including:  "
echo -e "   ifconfig, ping, netstat, traceroute, port scanning, DNS lookup, finger, whois"
echo -e " PuTTY Terminal Emulator - an X terminal emulator based on the popular Windows "
echo -e "   SSH client, PuTTY"
echo -e " Redshift - adjusts the color temperature of your screen according to your sur- "
echo -e "   roundings "
echo -e " Seahore - a GNOME application for managing encryption keys"
echo -e " SiriKali - a Qt/C++ GUI front end to cryfs,gocryptfs,securefs and encfs, allowing"
echo -e "   the user to create, mount, and unmount encrypted volumes"
echo -e " Terminator - Multiple terminals in one window"
echo -e " Tilda - a highly-configurable drop-down terminal emulator"
echo -e " GNOME To Do - a task management application designed to integrate with GNOME"
echo -e " UPnP Router Control - allows one to see some parameters of the router like: the "
echo -e "   network speed, the external IP and the model name"
echo -e " Vim - Vim - an almost compatible version of the UNIX editor Vi"
echo -e " +Visual Studio Code - a new choice of tool that combines the simplicity of a "
echo -e "   code editor with what developers need for the core edit-build-debug cycle"
echo -e " VirtualBox - a free x86 virtualization solution allowing a wide range of x86 "
echo -e "   operating systems such as Windows, DOS, BSD or Linux to run on a Linux system"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "                   ****** VirtualBox ******                                      "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Miscellaneous ******                   "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
echo -e " The following software packages are about to be installed. (*) specify packages "
echo -e " already installed on your system or packages that maybe be broken or uncompatible"
echo -e " with your system. Edit this script to install (*) packages."
echo -e ""
echo -e " CHIRP -  a free, open-source tool for programming your amateur radio."
echo -e "   http://chirp.danplanet.com/projects/chirp/wiki/Download"
echo -e " Clam AV - anti-virus utility for Unix - command-line interface "
echo -e " Dropbox - sync files between computers"
echo -e " Etcher - Flash OS images to SD cards & USB drives, safely and easily "
echo -e " Git - fast, scalable, distributed revision control system"
echo -e " gitkraken - Git client should integrate with your Git hosting service"
echo -e " gpa - GNU Privacy Guard, a free-software replacement for Symantec's PGP crypto-"
echo -e "   graphic software suite"
echo -e " gparted - GNOME partition editor"
echo -e " grsync -  a simple graphical interface using GTK2 for the rsync command line program"
echo -e " gufw Firewall - graphical user interface for ufw"
echo -e " ImageMagick - image manipulation programs"
echo -e " MeduLibre - an advanced menu editor that provides modern features"
echo -e " NTFS-3G - Read/Write NTFS Support"
echo -e " NTFS Configuration Tool - allow you to easily configure all of your NTFS devices to "
echo -e "  allow write support via a friendly gui"
echo -e " OpenConnect - VPN client that utilizes TLS and DTLS for secure session establishment "
echo -e "   and is compatible with the CISCO AnyConnect SSL VPN protocol"
echo -e ""
echo -e " PowerShell - an automation and configuration management platform. It consists of a "
echo -e "  cross-platform (Windows, Linux, and macOS) command-line shell and associated "
echo -e "  scripting language"
echo -e " rar - Archiver for .rar files"
echo -e " unrar - Unarchiver for .rar files (non-free version)"
echo -e " Stacer - "
echo -e " ttf-mscorefonts-installer - Installer for Microsoft TrueType core fonts"
echo -e " UNetbootin - allows for the installation of various Linux/BSD distributions to a "
echo -e "   partition or USB drive"
echo -e " VeraCrypt - a free and open-source utility used for on-the-fly encryption"
echo -e " xrdp - An open source remote desktop protocol(rdp) server"
echo -e " zip - Archiver for .zip files"
echo -e " unzip - De-archiver for .zip files "
echo -e ""
echo -e " ubuntu-restricted-extras - Commonly used restricted packages for Ubuntu"
echo -e " libavcodec-extra - FFmpeg codec library (additional codecs meta-package)"
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** Etcher ****** "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** PowerShell ****** "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** Stacer ****** "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** UNetbootin ****** "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "               ****** VeraCrypt ****** "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Finish Build Complete ******                                  "
echo -e "---------------------------------------------------------------------------------"
echo -e ""
sleep 3
echo -e ""
clear 																			 		# clear Screen
echo -e ""
echo -e "---------------------------------------------------------------------------------"
echo -e "            ****** Final System Update ******                                    "
echo -e "---------------------------------------------------------------------------------"
echo -e ""

